### ISSUE TITLE
You probably don't want to push your email address to a public repo

### ISSUE THREAD

**Issue by Einliterflasche** [Vostanis/pudb#1]
Hey,
first of all thank you for using my library `pg-worm`!
You really shouldn't push your api keys to a public repo (pudb); anyone could use them now. I suggest changing them immediately and not pushing your new keys. I found your email address in your source code as well.

**Comment by Vostanis** [comment]
Heya, yeah got lazy and needed to push it before i left for travels!! Thanks for reminding me, it's p cool to know people are so helpful on this website

Really cool library as well! I actually decided to use tokio-postgres just so I understood the primitive side of things first, but I think I'm gonna try the switch over to your crate soon

**Comment by Einliterflasche** [comment]
I just had a look at your actual code and I don't think pg-worm can do all that you need. Thanks for considering it though :)
